import React, { Fragment } from "react";
// import Header from "../Header/Header";
// import Footer from "../Footer/Footer";
import Head from "next/head";
import { CssBaseline } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import { theme } from "../../theme/theme";
const Layout = (props) => {
  return (
    <Fragment>
      <ThemeProvider theme={theme}>
      <CssBaseline />
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
          />
        </Head>

        {/* <Header /> */}
        <div>{props.children}</div>
        {/* <Footer /> */}
      </ThemeProvider>
    </Fragment>
  );
};

export default Layout;
